server.port=8081
spring.application.name=auth_cviper

spring.datasource.url=jdbc:postgresql://localhost:5432/auth_cviper
spring.datasource.username=postgres
spring.datasource.password=085279
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update