server.port=8082
spring.application.name=mail_cviper

spring.datasource.url=jdbc:postgresql://localhost:5432/mail_cviper
spring.datasource.username=postgres
spring.datasource.password=085279
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update