spring.application.name=cvalidator

spring.datasource.url=jdbc:postgresql://localhost:5432/cvalidator
spring.datasource.username=postgres
spring.datasource.password=085279
spring.datasource.driver-class-name=org.postgresql.Driver

# não deixar o Hibernate criar tabelas
spring.jpa.hibernate.ddl-auto=none

# executar schema.sql automaticamente
spring.sql.init.mode=always

# evita problemas de ordem de inicialização
spring.jpa.defer-datasource-initialization=true

# logs (opcional)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true